// Generado por `npm run blob:upload` (o script one-off). No editar a mano.
// Mapea id de video -> URL pública en Vercel Blob.
export const videoSrcs: Record<string, string> = {
  "1": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/1.mp4",
  "2": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/2.mp4",
  "3": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/3.mp4",
  "4": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/4.mp4",
  "5": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/5.mp4",
  "6": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/6.mp4",
  "7": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/7.mp4",
  "8": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/8.mp4",
  "9": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/9.mp4",
  "10": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/10.mp4",
  "11": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/11.mp4",
  "12": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/12.mp4",
  "13": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/13.mp4",
  "14": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/14.mp4",
  "15": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/15.mp4",
  "16": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/16.mp4",
  "17": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/17.mp4",
  "18": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/18.mp4",
  "19": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/19.mp4",
  "20": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/20.mp4",
  "21": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/21.mp4",
  "22": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/22.mp4",
  "23": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/23.mp4",
  "24": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/24.mp4",
  "25": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/25.mp4",
  "26": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/26.mp4",
  "27": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/27.mp4",
  "28": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/28.mp4",
  "29": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/29.mp4",
  "30": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/30.mp4",
  "31": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/31.mp4",
  "32": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/32.mp4",
  "33": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/33.mp4",
  "34": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/34.mp4",
  "35": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/35.mp4",
  "36": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/36.mp4",
  "37": "https://3l2scxmqzx27frgf.public.blob.vercel-storage.com/videos/37.mp4",
};
